package api

import (
	"bytes"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"gradpqc/cbom"
	"gradpqc/db"
	"gradpqc/montecarlo"
	"mime/multipart"
	"net/http"
	"net/smtp"
	"net/textproto"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// ScheduleRequest is the JSON body for POST /api/reports/schedule.
type ScheduleRequest struct {
	ReportType    string `json:"reportType"`
	Frequency     string `json:"frequency"`
	Assets        string `json:"assets"`
	DeliveryEmail string `json:"email"`
	Time          string `json:"time"`
}

func setCORSHeaders(w http.ResponseWriter) {
	w.Header().Set("Access-Control-Allow-Origin", "*")
	w.Header().Set("Access-Control-Allow-Methods", "GET, POST, OPTIONS")
	w.Header().Set("Access-Control-Allow-Headers", "Content-Type")
}

// HandleScheduleReport handles POST /api/reports/schedule.
func HandleScheduleReport(w http.ResponseWriter, r *http.Request) {
	setCORSHeaders(w)
	if r.Method == http.MethodOptions {
		w.WriteHeader(http.StatusOK)
		return
	}
	if r.Method != http.MethodPost {
		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
		return
	}

	var req ScheduleRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		http.Error(w, "Invalid JSON: "+err.Error(), http.StatusBadRequest)
		return
	}

	_, err := db.DB.Exec(
		`INSERT INTO scheduled_reports (report_type, frequency, assets_scope, delivery_email, scheduled_time)
		 VALUES (?, ?, ?, ?, ?)`,
		req.ReportType, req.Frequency, req.Assets, req.DeliveryEmail, req.Time,
	)
	if err != nil {
		http.Error(w, "Failed to save schedule: "+err.Error(), http.StatusInternalServerError)
		return
	}

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(map[string]string{
		"message":   "Report scheduled successfully",
		"frequency": req.Frequency,
		"time":      req.Time,
		"email":     req.DeliveryEmail,
	})
}

// HandleDownloadReport handles POST /api/reports/download.
// Body: { reportType, format ("json"|"excel"), email? }
// If email is set: generates the file and emails it.
// If email is empty: forces a browser file download.
func HandleDownloadReport(w http.ResponseWriter, r *http.Request) {
	setCORSHeaders(w)
	if r.Method == http.MethodOptions {
		w.WriteHeader(http.StatusOK)
		return
	}
	if r.Method != http.MethodPost {
		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
		return
	}

	var req struct {
		ReportType string `json:"reportType"`
		Format     string `json:"format"`
		Email      string `json:"email"`
	}
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		http.Error(w, "Invalid JSON: "+err.Error(), http.StatusBadRequest)
		return
	}

	format := strings.ToLower(strings.TrimSpace(req.Format))

	assets, err := db.FetchLatestResults()
	if err != nil {
		http.Error(w, "Failed to fetch scan results: "+err.Error(), http.StatusInternalServerError)
		return
	}
	if len(assets) == 0 {
		http.Error(w, "No scan results found. Run a scan first.", http.StatusNotFound)
		return
	}
	for i := range assets {
		montecarlo.ComputeMonteCarlo(&assets[i])
	}
	report := cbom.NewCBOM(assets)

	var (
		data     []byte
		filename string
		mimeType string
	)

	switch format {
	case "json":
		data, err = json.MarshalIndent(report, "", "  ")
		filename = "cbom_report.json"
		mimeType = "application/json"
	case "excel":
		data, err = cbom.ExportExcelBytes(report)
		filename = "cbom_report.xlsx"
		mimeType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
	default:
		http.Error(w, "Unsupported format. Use 'json' or 'excel'.", http.StatusBadRequest)
		return
	}

	if err != nil {
		http.Error(w, "Failed to generate report: "+err.Error(), http.StatusInternalServerError)
		return
	}

	email := strings.TrimSpace(req.Email)
	if email != "" {
		subject := fmt.Sprintf("GradPQC %s Report", req.ReportType)
		body := fmt.Sprintf(
			"Your on-demand GradPQC report is attached.\n\nReport: %s\nFormat: %s\n\nGenerated by GradPQC – PNB Cybersecurity Hackathon 2026\nNIST IR 8547 | RBI Cyber Security Framework Aligned",
			req.ReportType, strings.ToUpper(format),
		)
		if err := sendEmailAttachment(email, subject, body, filename, data, mimeType); err != nil {
			http.Error(w, "Failed to send email: "+err.Error(), http.StatusInternalServerError)
			return
		}
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(map[string]string{
			"message": "Report sent successfully to " + email,
		})
		return
	}

	// No email – force browser download
	w.Header().Set("Content-Type", mimeType)
	w.Header().Set("Content-Disposition", fmt.Sprintf(`attachment; filename="%s"`, filename))
	w.Header().Set("Cache-Control", "no-cache")
	w.Write(data)
}

// StartCronScheduler launches a background goroutine that checks every minute
// for scheduled reports that are due and emails them.
func StartCronScheduler() {
	ticker := time.NewTicker(1 * time.Minute)
	go func() {
		for range ticker.C {
			runScheduledReports()
		}
	}()
	fmt.Println("[cron] scheduled-report engine started (interval: 1 min)")
}

type scheduledRow struct {
	ID            int
	ReportType    string
	Frequency     string
	AssetsScope   string
	DeliveryEmail string
	ScheduledTime string
}

func runScheduledReports() {
	ist := time.FixedZone("IST", 5*60*60+30*60)
	now := time.Now().In(ist)
	currentHHMM := fmt.Sprintf("%02d:%02d", now.Hour(), now.Minute())

	rows, err := db.DB.Query(`
		SELECT id, report_type, frequency, assets_scope, delivery_email, scheduled_time
		FROM scheduled_reports
		WHERE delivery_email != ''
		  AND (last_sent_at IS NULL OR last_sent_at < DATE_SUB(NOW(), INTERVAL 23 HOUR))
	`)
	if err != nil {
		fmt.Printf("[cron] db query error: %v\n", err)
		return
	}
	defer rows.Close()

	for rows.Next() {
		var sr scheduledRow
		if err := rows.Scan(&sr.ID, &sr.ReportType, &sr.Frequency, &sr.AssetsScope, &sr.DeliveryEmail, &sr.ScheduledTime); err != nil {
			continue
		}
		if !isReportDue(sr.Frequency, sr.ScheduledTime, currentHHMM, now) {
			continue
		}
		if err := dispatchScheduledReport(sr); err != nil {
			fmt.Printf("[cron] failed to send id=%d to %s: %v\n", sr.ID, sr.DeliveryEmail, err)
			continue
		}
		db.DB.Exec("UPDATE scheduled_reports SET last_sent_at = NOW() WHERE id = ?", sr.ID)
		fmt.Printf("[cron] sent %s %s report → %s\n", sr.Frequency, sr.ReportType, sr.DeliveryEmail)
	}
}

func isReportDue(frequency, scheduledTime, currentHHMM string, now time.Time) bool {
	if scheduledTime != currentHHMM {
		return false
	}
	switch strings.ToLower(frequency) {
	case "daily":
		return true
	case "weekly":
		return now.Weekday() == time.Monday
	case "monthly":
		return now.Day() == 1
	}
	return false
}

func dispatchScheduledReport(sr scheduledRow) error {
	assets, err := db.FetchLatestResults()
	if err != nil {
		return fmt.Errorf("failed to fetch scan results: %w", err)
	}
	if len(assets) == 0 {
		return fmt.Errorf("no scan results found (run a scan first)")
	}
	for i := range assets {
		montecarlo.ComputeMonteCarlo(&assets[i])
	}
	report := cbom.NewCBOM(assets)

	data, err := json.MarshalIndent(report, "", "  ")
	if err != nil {
		return fmt.Errorf("failed to marshal report: %w", err)
	}

	subject := fmt.Sprintf("GradPQC Scheduled Report: %s (%s)", sr.ReportType, sr.Frequency)
	body := fmt.Sprintf(
		"Your %s scheduled %s report is attached.\n\nScope: %s\n\nGenerated by GradPQC – PNB Cybersecurity Hackathon 2026.\nNIST IR 8547 | RBI Cyber Security Framework Aligned.",
		sr.Frequency, sr.ReportType, sr.AssetsScope,
	)
	return sendEmailAttachment(sr.DeliveryEmail, subject, body, "cbom_report.json", data, "application/json")
}

// sendEmailAttachment sends an email with one file attachment.
// Configure via: SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASS in .env
func sendEmailAttachment(to, subject, body, filename string, attachment []byte, mimeType string) error {
	host := os.Getenv("SMTP_HOST")
	port := os.Getenv("SMTP_PORT")
	user := os.Getenv("SMTP_USER")
	pass := os.Getenv("SMTP_PASS")

	if host == "" {
		return fmt.Errorf("SMTP not configured – set SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASS in backend/.env")
	}
	if port == "" {
		port = "587"
	}

	var buf bytes.Buffer
	mw := multipart.NewWriter(&buf)

	// Plain-text body part
	th := make(textproto.MIMEHeader)
	th.Set("Content-Type", "text/plain; charset=utf-8")
	tw, _ := mw.CreatePart(th)
	fmt.Fprint(tw, body)

	// Attachment part (base64)
	ah := make(textproto.MIMEHeader)
	ah.Set("Content-Type", mimeType)
	ah.Set("Content-Disposition", fmt.Sprintf(`attachment; filename="%s"`, filepath.Base(filename)))
	ah.Set("Content-Transfer-Encoding", "base64")
	aw, _ := mw.CreatePart(ah)
	fmt.Fprint(aw, base64.StdEncoding.EncodeToString(attachment))
	mw.Close()

	raw := fmt.Sprintf(
		"From: GradPQC <%s>\r\nTo: %s\r\nSubject: %s\r\nMIME-Version: 1.0\r\nContent-Type: multipart/mixed; boundary=%s\r\n\r\n%s",
		user, to, subject, mw.Boundary(), buf.String(),
	)

	auth := smtp.PlainAuth("", user, pass, host)
	return smtp.SendMail(host+":"+port, auth, user, []string{to}, []byte(raw))
}
